---
title: "Multi-class ROML cross-validation"
author: "Poon Chi Lam"
date: "8/9/2019"
output: html_document
---

There are three models proposed:

- Model 1: one vs all other
- Model 2: pairwise comparison
- Model 3: pairwise comparison + objective function

```{R setup}
suppressPackageStartupMessages({
  library(tidyr)
  library(dplyr)
  library(reshape2)
  library(ggplot2)
  library(ggpubr)
  library(caret)
  library(pROC)
  library(stringr)
  library(randomForest)
})
source('~/ktsp/script/function/plot.utils.R')
source('~/ktsp/script/function/cross.platform.norm.R')
source('~/ktsp/script/function/lowMeans.filter.R')
source('~/ktsp/script/function/merge.kpairs.R')
source('~/ktsp/script/function/multi.rf.cv.R')
```



### load data
```{R}
load('~/ktsp/data/multiclass/realdata/imbalanced/BRCA.multi.Rdata')
load('~/ktsp/data/multiclass/realdata/imbalanced/MB.multi.Rdata')

lb.brca <- factor(mul.brca.clin$final_assign)
lb.mb <- factor(mul.mb.clin$Pam50Subtype)

Ks <- c(20, 50, 100, 300, 500, 1000)
```


## TCGA as training
### Cross-validation 
#### Model 1

Here is the model 1, firstly is to calculate gene pair scores between each class and all others:

1. Basal vs. others 
2. Her2 vs. others 
3. LumA vs. others 
4. LumB vs. others 

Then we select `k` pairs for each comparison, get totally ~5k gene pairs, after that their ranks are binarized into `0` or `1` as binary feature input, finally dump into a random forest model.

```{R}
# low mean filtering
gene.keep <- lowMeans.filter(mul.brca.expr, 70)
brca.train <- mul.brca.expr[match(gene.keep, rownames(mul.brca.expr)), ]

grp <- factor(mul.brca.clin$final_assign)
grp.names <- levels(grp)
```

```{R, eval=F}
## load the scores calculated before
score.dir <- "~/ktsp/data/multiclass/realdata/imbalanced/score/tcga"
tcga.tsp <- list()
for (class in grp.names) {
  load(file.path(score.dir, paste0(class, '.score.Rdata')))
  colnames(tsp) <- c('score', 'geneX', 'geneY')
  tcga.tsp[[class]] <- tsp[c(1:max(Ks)),]
}

tcga.kpairs <- merge.kpairs(Ks = Ks, 
                            tsp.list = tcga.tsp, 
                            no.model = 1)

tcga.cv.m1 <- list()
for (K in Ks) {
  print(paste0('---- K = ', K))
  tcga.cv.m1[[as.character(K)]] <- multi.rf.cv(dataframe=as.data.frame(t(brca.train)), 
                                              label=lb.brca, 
                                              K=K, 
                                              kpairs=tcga.kpairs, 
                                              grp.names=grp.names,
                                              model.no=1, 
                                              time=10)
}
save(tcga.cv.m1, file='~/ktsp/data/multiclass/realdata/imbalanced/multi.results/tcga.cv.m1.Rdata')
```


#### Model 2
Pairwise ktsp score calculation -> select features -> random forest

```{R}
## load the scores calculated before
score.dir <- "~/ktsp/data/multiclass/realdata/imbalanced/score/tcga"
tcga.tsp <- list()
for (i in 1:(length(grp.names)-1)) {
  for (j in (i+1):length(grp.names)) {
    comp <- paste0(grp.names[i], "_", grp.names[j])
    load(file.path(score.dir, paste0(comp, ".score.Rdata")))
    colnames(tsp) <- c('score', 'geneX', 'geneY')
    tcga.tsp[[comp]] <- tsp[c(1:max(Ks)),]
  }
}
```

```{R, eval=F}
tcga.kpairs <- merge.kpairs(Ks = Ks, 
                            tsp.list = tcga.tsp, 
                            no.model = 2)

tcga.cv.m2 <- list()
for (K in Ks) {
  print(paste0('---- K = ', K))
  tcga.cv.m2[[as.character(K)]] <- multi.rf.cv(dataframe=as.data.frame(t(brca.train)), 
                                              label=lb.brca, 
                                              K=K, 
                                              kpairs=tcga.kpairs, 
                                              grp.names=grp.names,
                                              model.no=2, 
                                              time=10)
}
save(tcga.cv.m2, file='~/ktsp/data/multiclass/realdata/imbalanced/multi.results/tcga.cv.m2.Rdata')
```


#### Model 3
Pairwise ktsp score calculation -> select features -> random forest

```{R, eval=F}
## load the scores calculated before
tcga.kpairs <- merge.kpairs(Ks = Ks, 
                            tsp.list = tcga.tsp, 
                            no.model = 3)

tcga.cv.m3 <- list()
for (K in Ks) {
  print(paste0('---- K = ', K))
  tcga.cv.m3[[as.character(K)]] <- multi.rf.cv(dataframe=as.data.frame(t(brca.train)), 
                                              label=lb.brca, 
                                              K=K, 
                                              grp.names=grp.names,
                                              kpairs=tcga.kpairs, 
                                              model.no=3, 
                                              time=1)
}
save(tcga.cv.m3, file='~/ktsp/data/multiclass/realdata/imbalanced/multi.results/tcga.cv.m3.Rdata')
```



## MetaBric as training
### Cross-validation 
#### Model 1

```{R}
# low mean filtering
gene.keep <- lowMeans.filter(mul.mb.expr, 70)
mb.train <- mul.mb.expr[match(gene.keep, rownames(mul.mb.expr)), ]

grp <- factor(mul.mb.clin$Pam50Subtype)
grp.names <- levels(grp)

## load the scores calculated before
score.dir <- "~/ktsp/data/multiclass/realdata/imbalanced/score/metabric"
mb.tsp <- list()
for (class in grp.names) {
  load(file.path(score.dir, paste0(class, '.score.Rdata')))
  colnames(tsp) <- c('score', 'geneX', 'geneY')
  mb.tsp[[class]] <- tsp[c(1:max(Ks)),]
}

mb.kpairs <- merge.kpairs(Ks = Ks, 
                          tsp.list = mb.tsp, 
                          no.model = 1)

mb.cv.m1 <- list()
for (K in Ks) {
  print(paste0('---- K = ', K))
  mb.cv.m1[[as.character(K)]] <- multi.rf.cv(dataframe=as.data.frame(t(mb.train)), 
                                              label=lb.mb, 
                                              K=K, 
                                              kpairs=mb.kpairs, 
                                              grp.names=grp.names,
                                              model.no=1, 
                                              time=10)
}
save(mb.cv.m1, file='~/ktsp/data/multiclass/realdata/imbalanced/multi.results/mb.cv.m1.Rdata')
```


#### Model 2
```{R}
## load the scores calculated before
mb.tsp <- list()
for (i in 1:(length(grp.names)-1)) {
  for (j in (i+1):length(grp.names)) {
    comp <- paste0(grp.names[i], "_", grp.names[j])
    load(file.path(score.dir, paste0(comp, ".score.Rdata")))
    colnames(tsp) <- c('score', 'geneX', 'geneY')
    mb.tsp[[comp]] <- tsp[c(1:max(Ks)),]
  }
}

mb.kpairs <- merge.kpairs(Ks = Ks, 
                          tsp.list = mb.tsp, 
                          no.model = 2)

mb.cv.m2 <- list()
for (K in Ks) {
  print(paste0('---- K = ', K))
  mb.cv.m2[[as.character(K)]] <- multi.rf.cv(dataframe=as.data.frame(t(mb.train)), 
                                              label=lb.mb, 
                                              K=K, 
                                              kpairs=mb.kpairs, 
                                              grp.names=grp.names,
                                              model.no=2, 
                                              time=10)
}
save(mb.cv.m2, file='~/ktsp/data/multiclass/realdata/imbalanced/multi.results/mb.cv.m2.Rdata')
```


#### Model 3
Pairwise ktsp score calculation -> select features -> random forest

```{R, eval=T}
## load the scores calculated before
mb.kpairs <- merge.kpairs(Ks = Ks, 
                          tsp.list = mb.tsp, 
                          no.model = 3)

mb.cv.m3 <- list()
for (K in Ks) {
  print(paste0('---- K = ', K))
  mb.cv.m3[[as.character(K)]] <- multi.rf.cv(dataframe=as.data.frame(t(mb.train)), 
                                             label=lb.mb, 
                                             K=K, 
                                             kpairs=mb.kpairs, 
                                             grp.names=grp.names,
                                             model.no=3, 
                                             time=1)
}
save(mb.cv.m3, file='~/ktsp/data/multiclass/realdata/imbalanced/multi.results/mb.cv.m3.Rdata')
```


## See the results
```{R}
Ks <- c(20, 50, 100, 300, 500, 1000)
res.dir <- '~/ktsp/data/multiclass/realdata/imbalanced/multi.results'

# tcga m1
load(file.path(res.dir, 'tcga.cv.m1.Rdata'))
print('tcga m1')
for (K in Ks) {
  yd.df <- tcga.cv.m1[[as.character(K)]][["all.youden"]]
  print(mean(yd.df$meanV))
}


# tcga m2
load(file.path(res.dir, 'tcga.cv.m2.Rdata'))
print('tcga m2')
for (K in Ks) {
  yd.df <- tcga.cv.m2[[as.character(K)]][["all.youden"]]
  print(mean(yd.df$meanV))
}


# mb m1
load(file.path(res.dir, 'mb.cv.m1.Rdata'))
print('mb m1')
for (K in Ks) {
  yd.df <- mb.cv.m1[[as.character(K)]][["all.youden"]]
  print(mean(yd.df$meanV))
}


# mb m2
load(file.path(res.dir, 'mb.cv.m2.Rdata'))
print('mb m2')
for (K in Ks) {
  yd.df <- mb.cv.m2[[as.character(K)]][["all.youden"]]
  print(mean(yd.df$meanV))
}


```
